### ISSUE TITLE
Where does this install to and how can I tweak it?

### ISSUE THREAD

**Issue by stoeckley** [cayennes/solarized-parentheses-lighttable-theme#1]
Hi -- just installed this; it appears in my themes list upon restart of LT but I cannot figure out where on OSX this is actually installed as I'd like to look at it. I checked the themes and CSS directories in the application bundle. When I run it, there is some improvement in the parenthesis issue, but but there is a dotted box around any comments in a source file; additionally, all syntax highlighting disappears when this is enabled.

**Comment by cayennes** [comment]
Sorry I didn't notice this.  I'm sure this is way too late to be helpful, but: http://docs.lighttable.com/#plugins-directory
